### ISSUE TITLE
New name for this repo

### ISSUE THREAD

**Issue by rgantonio** [KULeuven-MICAS/HeMAiA#2]
Let's change this to a different name later. Make this issue a suggestion page? Feel free to modify!

Suggested names:

- [ ] SNAX-N ( SNAX Networks)
- [ ] Hemaia

**Comment by IveanEx** [comment]
Is it necessary to change the naming at the inside?

**Comment by rgantonio** [comment]
> Is it necessary to change the naming at the inside?

What do you mean inside? The system? No that will be too much haha but at least the repo 😄

**Comment by IveanEx** [comment]
Then we maybe change it to hemaia 😂😂

**Comment by rgantonio** [comment]
Woah woah waoh! We all take a vote for that haha
